USE tourism_app;

INSERT IGNORE INTO categories (name) VALUES
  ('Todos'),
  ('Monumentos'),
  ('Museus'),
  ('Natureza'),
  ('Religiosos'),
  ('Parques'),
  ('Arquitetura'),
  ('Praias'),
  ('Gastronomia'),
  ('Compras'),
  ('Vida Noturna'),
  ('Eventos'),
  ('Histórico'),
  ('Esportes'),
  ('Aventura'),
  ('Cultura'),
  ('Mirantes'),
  ('Passeios de Barco'),
  ('Cachoeiras'),
  ('Trilhas'),
  ('Entretenimento'),
  ('Ecoturismo'),
  ('Rural'),
  ('Tecnologia'),
  ('Arte Urbana'),
  ('Feiras'),
  ('Zoológicos'),
  ('Aquários'),
  ('Parques Temáticos'),
  ('Sítios Arqueológicos'),
  ('Patrimônio Mundial'),
  ('Passeios de Trem'),
  ('Cicloturismo'),
  ('Observação de Aves'),
  ('Pesca'),
  ('Golf'),
  ('Spa & Bem-estar'),
  ('Hotéis Históricos'),
  ('Castelos'),
  ('Mercados'),
  ('Festas Tradicionais');
